-- THRICIENCE XI.3 DATABASE
-- Jalankan di Supabase > SQL Editor

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  category text not null default 'Berita' check (category in ('Berita','Pengumuman','Prestasi')),
  excerpt text not null default '',
  content text not null default '',
  image_url text,
  author text,
  views integer not null default 0,
  published_at timestamptz not null default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  image_url text not null,
  caption text,
  created_at timestamptz not null default now()
);

alter table public.posts enable row level security;
alter table public.gallery enable row level security;

create policy "Public can read posts" on public.posts for select using (true);
create policy "Authenticated admins can insert posts" on public.posts for insert to authenticated with check (true);
create policy "Authenticated admins can update posts" on public.posts for update to authenticated using (true) with check (true);
create policy "Authenticated admins can delete posts" on public.posts for delete to authenticated using (true);

create policy "Public can read gallery" on public.gallery for select using (true);
create policy "Authenticated admins can insert gallery" on public.gallery for insert to authenticated with check (true);
create policy "Authenticated admins can delete gallery" on public.gallery for delete to authenticated using (true);

-- Buat storage bucket bernama media dari Storage, atau jalankan:
insert into storage.buckets (id, name, public) values ('media','media',true) on conflict (id) do nothing;

create policy "Public can view media" on storage.objects for select using (bucket_id = 'media');
create policy "Admins can upload media" on storage.objects for insert to authenticated with check (bucket_id = 'media');
create policy "Admins can delete media" on storage.objects for delete to authenticated using (bucket_id = 'media');

-- CONTOH BERITA
insert into public.posts (title,slug,category,excerpt,content,author) values
('Selamat Datang di Portal THRICIENCE XI.3','selamat-datang-di-portal-thricience-xi3','Berita','Website resmi informasi kelas XI.3.','Selamat datang di portal digital THRICIENCE XI.3. Website ini menjadi tempat berbagi berita, pengumuman, prestasi, dan dokumentasi kegiatan kelas.','Admin');
