'use client'
import { useEffect, useState } from 'react'
import { createClient } from '../../lib/supabase'

export default function Admin(){const supabase=createClient();const [session,setSession]=useState(null);const [posts,setPosts]=useState([]);const [form,setForm]=useState({title:'',category:'Berita',excerpt:'',content:'',image_url:''});const [file,setFile]=useState(null);const [msg,setMsg]=useState('');
useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub.subscription.unsubscribe()},[])
async function load(){const {data}=await supabase.from('posts').select('*').order('published_at',{ascending:false});setPosts(data||[])}
useEffect(()=>{if(session)load()},[session])
async function login(e){e.preventDefault();const email=e.target.email.value,password=e.target.password.value;const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMsg(error.message)}
async function logout(){await supabase.auth.signOut();setSession(null)}
async function publish(e){e.preventDefault();setMsg('Menyimpan...');let image=form.image_url;if(file){const ext=file.name.split('.').pop();const path=`${Date.now()}.${ext}`;const up=await supabase.storage.from('media').upload(path,file,{upsert:false});if(up.error){setMsg(up.error.message);return}image=supabase.storage.from('media').getPublicUrl(path).data.publicUrl}const slug=form.title.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+Date.now();const {error}=await supabase.from('posts').insert({title:form.title,slug,category:form.category,excerpt:form.excerpt,content:form.content,image_url:image,author:session.user.email});if(error)setMsg(error.message);else{setMsg('Berita berhasil diterbitkan!');setForm({title:'',category:'Berita',excerpt:'',content:'',image_url:''});setFile(null);load()}}
async function del(id){if(!confirm('Hapus berita ini?'))return;const {error}=await supabase.from('posts').delete().eq('id',id);if(error)setMsg(error.message);else load()}
if(!session)return <main className="admin"><div className="admin-login"><span className="eyebrow">THRICIENCE ADMIN</span><h1>Login Admin</h1><p>Gunakan email dan password akun Supabase yang kamu buat untuk admin.</p><form onSubmit={login}><input name="email" type="email" placeholder="Email admin" required/><input name="password" type="password" placeholder="Password" required/><button className="btn primary">Masuk</button></form>{msg&&<p className="error">{msg}</p>}</div></main>
return <main className="admin"><div className="container"><div className="admin-top"><div><span className="eyebrow">DASHBOARD</span><h1>THRICIENCE Admin</h1></div><button onClick={logout} className="btn ghost">Keluar</button></div><div className="admin-grid"><form className="editor" onSubmit={publish}><h2>Tambah Info / Berita</h2><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Judul berita" required/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option>Berita</option><option>Pengumuman</option><option>Prestasi</option></select><input value={form.excerpt} onChange={e=>setForm({...form,excerpt:e.target.value})} placeholder="Ringkasan singkat" required/><textarea value={form.content} onChange={e=>setForm({...form,content:e.target.value})} placeholder="Isi berita..." rows="10" required/><input value={form.image_url} onChange={e=>setForm({...form,image_url:e.target.value})} placeholder="URL foto (opsional)"/><label className="file">Atau upload foto<input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="btn primary">Publikasikan</button>{msg&&<p>{msg}</p>}</form><section className="admin-list"><h2>Berita Terbit</h2>{posts.map(p=><div className="admin-item" key={p.id}><div><b>{p.title}</b><small>{p.category} • {new Date(p.published_at).toLocaleDateString('id-ID')}</small></div><button onClick={()=>del(p.id)}>Hapus</button></div>)}</section></div></div></main>}
